### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by fadhly-permata** [octapush/octapushJS#1]
- [ ] Expanding _number_ method
- [ ] Adding _object_ handling support
- [ ] Adding _collection_ handling support

**Comment by fadhly-permata** [comment]
Hai anyone, please give me any data type handling to next enhancement of this library. Thanks
